name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install ni
        run: npm i -g @antfu/ni

      - name: Install dependencies
        id: dependencies
        run: nci

      - name: Lint
        if: steps.dependencies.outcome == 'success'
        run: nr lint
