name: Build and release

on: [push]

jobs:
  # If a new version tag is created, create a GitHub release
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Release
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Build extension zip file
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        id: dependencies
        run: pnpm i --frozen-lockfile --ignore-scripts

      - name: Calculate postfix
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        id: postfix
        run: |
          echo "postfix=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build zip for Chrome
        id: chrome-zip
        run: |
          pnpm run zip:chrome "${{ steps.postfix.outputs.postfix }}"
          CHROME_ZIP_PATH=$(ls package/*-chrome*.zip)
          echo "path=$CHROME_ZIP_PATH" >> $GITHUB_OUTPUT

      - name: Add zip for Chrome as artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension
          path: ${{ steps.chrome-zip.outputs.path }}

      - name: Build zip for Firefox
        id: firefox-zip
        run: |
          pnpm run zip:firefox "${{ steps.postfix.outputs.postfix }}"
          FIREFOX_ZIP_PATH=$(ls package/*-firefox*.zip)
          echo "path=$FIREFOX_ZIP_PATH" >> $GITHUB_OUTPUT

      - name: Add zip for Firefox as artifact
        uses: actions/upload-artifact@v4
        with:
          name: firefox-extension
          path: ${{ steps.firefox-zip.outputs.path }}

      - name: Add zip for Chrome and Firefox to release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.chrome-zip.outputs.path }}
            ${{ steps.firefox-zip.outputs.path }}
          token: ${{ secrets.GITHUB_TOKEN }}
